version: '3.7'

networks:
  default:

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-${ENV}:/etc/nginx/sites-enabled:ro
      - ./app:/app
    logging: 
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - php

  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      target: dev
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
        - PECL_XDEBUG_INSTALL_SUFFIX
        - PECL_MONGODB_INSTALL_SUFFIX
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    container_name: php
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
      - DB_HOST=${MYSQL_HOST}
      - DB_NAME=${MYSQL_DB_NAME}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./tests:/tests:delegated
      - ./yii2:/yii2:delegated
      - ./app:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      default:
        aliases:
          - php

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    restart: always 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8765:80
    links:
      - mysql:db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    logging: 
      options:
        max-size: "5m"
        max-file: "5"
    depends_on:
      - mysql
    restart: always